### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by samsamai**

### CODE REVIEW

**Comment by billy1624** [comment]
It's better to have a github action to at least compile the rocket starter if running it with live db connection is difficult.

**Comment by samsamai** [comment]
> It's better to have a github action to at least compile the rocket starter if running it with live db connection is difficult.

I'll take a look at getting the tests going on the CI.

**Comment by samsamai** [comment]
> It's better to have a github action to at least compile the rocket starter if running it with live db connection is difficult.

Done

**Review by tyt2y3 — APPROVED** [review]

**Comment by tyt2y3** [comment]
Thank you so much for the great work!

**Comment by billy1624** [comment]
Hey @samsamai, thank you so much for the contributions :)

**Pull request merged**
